myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/urls.py
from django.urls import path, include
from . import views


app_name = "bitruschoji4realscrumy"
urlpatterns = [
    path('', views.index, name='index'),
    path("movegoal/<int:goal_id>", views.move_goal, name="move_goal"),
    path("addgoal/", views.add_goal, name="add_goal"),
    path("home/", views.home, name="home"),
    path('accounts/', include("django.contrib.auth.urls")),
    ]

myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bitruschoji4realscrumy/', include('django-bitruschoji4realscrumy.bitruschoji4realscrumy.urls')),
    path('websocket/', include('websocket.urls')), 

]

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ScrumyGoals(models.Model):
    # class Meta:
    #     verbose_name_plural = "Scrumy Goals"
    goal_name = models.CharField(max_length=300)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length=300)
    moved_by = models.CharField(max_length=300)
    owner = models.CharField(max_length=300)
    goal_status=models.ForeignKey(to='GoalStatus', related_name="goals", on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="users")

    def __str__(self):
        return self.goal_name
    

class ScrumyHistory(models.Model):
    # class Meta:
    #     verbose_name_plural = "Scrumy History"
    moved_by = models.CharField(max_length=300)
    created_by = models.CharField(max_length=300)
    moved_from = models.CharField(max_length=300)
    moved_to = models.CharField(max_length=300)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.CASCADE) 
    
    def __str__(self):
        return self.created_by

class GoalStatus(models.Model):
    # class Meta:
    #     verbose_name_plural = "GoalStatus"
    status_name = models.CharField(max_length=300)

    def __str__(self):
        return self.status_name

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/forms.py
from django.forms import ModelForm, Form
from .models import User, GoalStatus, ScrumyGoals, ScrumyHistory
from django import forms

class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ["first_name","last_name","email","username","password"]
    
class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ["goal_name", "user"]


class MoveGoalForm(Form):
    choices = (('Daily Goal', 'Daily Goal'), ('Weekly Goal', 'Weekly Goal'), ('Done Goal', 'Done Goal'), ('Verify Goal', 'Verify Goal'))
    status_name = forms.ChoiceField(choices=choices)
    

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import  ScrumyGoals, GoalStatus
from django.contrib.auth.models import User
import random
from .forms import SignupForm, CreateGoalForm, MoveGoalForm
from django.contrib.auth.models import Group
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.contrib.auth import logout


# Create your views here.
def index(request): 
    # goal = ScrumyGoals.objects.filter(goal_name="Learn Django")
    # return HttpResponse(goal)
    form = SignupForm()
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.password = make_password(form.cleaned_data['password'])
            new_user.save()
        # return home(request)

            # developer = Group.objects.get(name="Developer")
            # new_user = User.objects.get(username=form.cleaned_data["username"])
            # developer.user_set.add(new_user)
            messages.success(request, "Account has been created successfully")
            return redirect("/bitruschoji4realscrumy/accounts/login", permanent=True)

    else:
        form = SignupForm()

    dictionary = {"form":form}
    return render(request, "bitruschoji4realscrumy/index.html", dictionary)



def move_goal(request, goal_id):
    
    try:
        goal = ScrumyGoals.objects.get(goal_id=goal_id)
        
    except Exception as e: 
    
        return render(request, "bitruschoji4realscrumy/exception.html", {"error":"A record with that goal id does not exist"})
    current_user = request.user
    if request.method == 'POST':
        form = MoveGoalForm(request.POST)
        if form.is_valid():

            if current_user.groups.filter(name="Developer").exists():
                if form.cleaned_data['status_name'] == "Done Goal":
                    messages.error(request, "you don't have permmission to perform this action.")
                    return redirect('bitruschoji4realscrumy:home', permanent=True)
                if goal.user != current_user:
                    messages.error(request, """you don't have permmission to perform this action.
                    Try moving a goal you created""")
                    return redirect('bitruschoji4realscrumy:home', permanent=True)

            if current_user.groups.filter(name="Quality Assurance").exists():
                if form.cleaned_data['status_name'] == "Weekly Goal":
                    messages.error(request, "you don't have permmission to perform this action.")
                    return redirect('bitruschoji4realscrumy:home', permanent=True)
                if goal.user != current_user and goal.goal_status.status_name != "Verify Goal":
                    messages.error(request, "You can only move goals of others provided they have been verified")
                    return redirect('bitruschoji4realscrumy:home', permanent=True)

            if current_user.groups.filter(name="Owner").exists():
                if goal.user != current_user:
                    messages.error(request, """you don't have permmission to perform this action.
                    Try moving a goal you created""")
                    return redirect('bitruschoji4realscrumy:home', permanent=True)

            goal.goal_status = GoalStatus.objects.get(status_name=form.cleaned_data['status_name'])
            goal.save()
            messages.success(request, f"The goal has been sucessfully moved to {form.cleaned_data['status_name']}")
            return redirect('bitruschoji4realscrumy:home', permanent=True)

    else:
        #return HttpResponse(goal.goal_name)
        form = MoveGoalForm()
    return render(request, 'bitruschoji4realscrumy/movegoal.html', {'form':form})


def add_goal(request):
    # goal= GoalStatus.objects.get(status_name= 'Daily Goal')
    # myuser = User.objects.get(username='kim')
    # data = ScrumyGoals.objects.all()
    # for new_loop in data:
    #     random_id = random.randint(1000, 9999)
    #     if new_loop.goal_id != random_id:
    #         new_scrumy_goal = ScrumyGoals(goal_name ='Keep Learning Django',goal_id = random_id,
    #         created_by='kim', moved_by='kim', owner='kim', goal_status = goal,user=myuser)
    #         new_scrumy_goal.save()
    #         #return HttpResponse("Created")

    current_user = request.user
    if request.method == "POST":
        form = CreateGoalForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            if current_user.groups.first().name in ["Developer", "Quality Assurance", "Owner"]:
                if form.cleaned_data['user'] != current_user or \
                    form.cleaned_data['goal_status'].status_name != "Weekly Goal":
                    messages.error(request, "You can only create a weekly goal for yourself")
                    return render(request, 'addgoal.html', {'form': form})
            form.save()
            messages.success(request, "Goal has been successfully created")
            return redirect('bitruschoji4realscrumy:home', permanent=True)
    else:
        form = CreateGoalForm()

    return render(request, 'bitruschoji4realscrumy/addgoal.html', {'form': form})


def home(request):  
    # goal = ScrumyGoals.objects.get(goal_name='Learn Django')
    # dictionary = {"goal_name":goal.goal_name, "goal_id":goal.goal_id, "user":goal.user}    
    # return render(request, "bitruschoji4realscrumy/home.html", dictionary)
    # users = User.objects.all()
    # done_goal = GoalStatus.objects.get(status_name="Done  Goal").goals.all()
    # weekly_goal = GoalStatus.objects.get(status_name="Weekly Goal").goals.all()
    # daily_goal = GoalStatus.objects.get(status_name="Daily Goal").goals.all()
    # verify_goal = GoalStatus.objects.get(status_name="Verify Goal").goals.all()
    # dictionary = {
    # 'users':users,
    # 'weekly_goal': weekly_goal,
    # 'daily_goal': daily_goal,
    # 'verify_goal': verify_goal,
    # 'done_goal': done_goal,
    #}
    return render(request, "bitruschoji4realscrumy/home.html")


def logout_view(request):
    logout(request)
    redirect('bitruschoji4realscrumy:login', permanent=True)

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/templates/bitruschoji4realscrumy/addgoal.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>Add Goal</title>
        <link rel = "stylesheet" type = "text/css" href = "{% static 'form.css' %}" />
        <style>
            input[type=text], select {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: #4CAF50;
              color: white;
              padding: 14px 20px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: #45a049;
            }
            
            div {
              border-radius: 5px;
              background-color: #f2f2f2;
              padding: 20px;
            }
            </style>
    </head>
    <body>
        <h2><a href="{% url 'bitruschoji4realscrumy:home' %}">Home </a> <a href="{% url 'bitruschoji4realscrumy:logout' %}">Logout</a></h2>
        <p>Currrent User: {{ request.user }}</p>
        <p>Groups: {{ request.user.groups.first }}</p><br>

        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
          </ul>
        {% endif %}
        <p>This user can only create a goal for him/herself</p>
        <div>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.as_p  }}
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>
    </body>
</html>

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/templates/bitruschoji4realscrumy/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>{{ error }}</p>
</body>
</html>

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/templates/bitruschoji4realscrumy/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
<body>
        <p>Currrent User: {{ request.user }}</p>
        <p>Groups: {{ request.user.groups.first }}</p><br>
    <table>
        <thead>
            <tr>
                <th>User</th>
                <th>Weekly Goals</th>
                <th>Daily Goals</th>
                <th>Verify Goals</th>
                <th>Done Goals</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>
                    {% for goal in weekly_goal %}
                        {% if goal.user == user %}
                            {{ goal.goal_id }} <br> {{goal.goal_name}} <br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in daily_goal %}
                        {% if goal.user == user %}
                            {{ goal.goal_id }} <br> {{goal.goal_name}} <br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in verify_goal %}
                        {% if goal.user == user%}
                            {{ goal.goal_id }} <br> {{goal.goal_name}} <br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in done_goal %}
                        {% if goal.user == user %}
                            {{ goal.goal_id }} <br> {{goal.goal_name}} <br>
                        {% endif %} 
                    {% endfor %}
                </td>
            </tr>       
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'bitruschoji4realscrumy:add_goal' %}"> Add Goal </a> <br>
    
 
</body>
</html>

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/templates/bitruschoji4realscrumy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup Page</title>
</head>
<body>
    <h2>Signup Form</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Signup">
    </form>
    {% if form.errors %}
        <p>Invalid signup credentials
        {{ form.errors }}
        </p>
    {% endif %}
</body>
</html>

myscrumy/django-bitruschoji4realscrumy/bitruschoji4realscrumy/templates/bitruschoji4realscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Move Goal</title>
    <style>
        input[type=text], select {
          width: 100%;
          padding: 12px 20px;
          margin: 8px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 4px;
          box-sizing: border-box;
        }
        
        input[type=submit] {
          width: 100%;
          background-color: #4CAF50;
          color: white;
          padding: 14px 20px;
          margin: 8px 0;
          border: none;
          border-radius: 4px;
          cursor: pointer;
        }
        
        input[type=submit]:hover {
          background-color: #45a049;
        }
        
        div {
          border-radius: 5px;
          background-color: #f2f2f2;
          padding: 20px;
        }
    </style>

</head>
<body>
    <h2><a href="{% url 'bitruschoji4realscrumy:home' %}">Home </a> <a href="{% url 'bitruschoji4realscrumy:logout' %}">Logout</a></h2>
    <p>Currrent User: {{ request.user }}</p>
    <p>Groups: {{ request.user.groups.first }}</p><br>
      <div>
          <form action="" method="POST">
              {% csrf_token %}
              <p>Move to:</p><br>
              {{ form.as_p }}
              <input type="submit" name="submit" value="Submit">
          </form>
      </div>

</body>
</html>